# Generated by Django 4.1.4 on 2024-02-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
