# Generated by Django 4.1.4 on 2024-03-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_employees_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='image',
            new_name='profile_pic',
        ),
    ]
